### ISSUE TITLE
Coloured Name

### ISSUE THREAD

**Issue by Mag3YT** [m-byte918/MultiOgar-Edited#1509]
How Do I Add Colored Names?

Example Anyone Who Uses My Name "Mage"
Their Name Would Appear In Black

**Comment by Mag3YT** [comment]
Btw I dont Mind If Its  the cell that would be black

**Comment by Mag3YT** [comment]
is everyone dead? 







Hey Lemons

**Comment by AlexHGaming** [comment]
Client sided, you can however ask through the discord server.

**Comment by Niall7459** [comment]
1. You can use the colour sent for the cells colour as the nickname colour.
2. You can use the handy script Tombez wrote for Minecraft based colour codes in text. (e.g names, leaderboards using § colourcodes)

**Comment by Mag3YT** [comment]
Thanks
