### ISSUE TITLE
When changing the max split in GameServer.js, it doesn't actually affect the game settings.

### ISSUE THREAD

**Issue by chernxbyl42069** [m-byte918/MultiOgar-Edited#1517]
In fact, nothing I change in GameServer.js actually works.

**Comment by ItzLevvie** [comment]
You've to do your game server changes in [this file](https://github.com/m-byte918/MultiOgar-Edited/blob/master/src/gameserver.ini)

**Comment by ItzLevvie** [comment]
Which file did you actually edit? Did you restart the server to apply the newly set configuration?

**Comment by Borys64** [comment]
Sorry for the issues. Fixed. The values can now be edited in [`config.js`](https://github.com/m-byte918/MultiOgar-Edited/blob/master/src/config.js).
